version: '3'
services:
  client:
    build: ./client
    ports:
      - 3000:3000
    networks:
      - app-network

  server:
    build: ./server
    ports:
      - 8000:8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
